### ISSUE TITLE
How to verify the existence of the file?

### ISSUE THREAD

**Issue by impuulse** [hguenot/yii2-gftp#11]
Hello, I try to check existence of the file : Yii::$app->ftp->fileExists($filename) but false, although file exist and exist directory (i checked it with this function) where located this file. Directory ok, file in this directory can't see.

**Comment by ndobromirov** [comment]
Can it be due to file permissions?

**Comment by hguenot** [comment]
I think you need to chdir to expected folder before testing if file exists.

**Comment by schillaci** [comment]
Php 5.6 function` ftp_nlist `return empty array instead **false**
`\gftp\drivers\FtpDriver::fileExists` use function ftp_nlist
instead:
`return $res !== false;`
put: 
`return !empty($res);`
