### ISSUE TITLE
Use of undefined constant FTP_ASCII - assumed 'FTP_ASCII'

### ISSUE THREAD

**Issue by fbens** [hguenot/yii2-gftp#15]
PHP 7.1 + WIN7 
tips `Use of undefined constant FTP_ASCII - assumed 'FTP_ASCII'`

**Comment by hguenot** [comment]
Don't know why FTP_ASCII is not available in your environment. 
Please check if FTP extension is available and correctly loaded.

**Comment by fbens** [comment]
thank you,bcs php_ftp.dll is not enabled
