### ISSUE TITLE
Getting Folders with UTF-8 Charset

### ISSUE THREAD

**Issue by Shaeldon** [hguenot/yii2-gftp#16]
When trying to list all folders some contain utf-8 charakters which do not work. Is there a way to set the ftp-connection to utf-8?

Same goes for writing into Folders which contain special charakters ( ex. München ). I am not able to get into that folder.

**Comment by hguenot** [comment]
According to https://stackoverflow.com/questions/16759507/php-ftp-filename-encoding-issue#answer-30678185
You can try to call execute method on driver to execute `'OPTS UTF8 ON'` FTP command.

**Comment by hguenot** [comment]
Hi Shaeldon,

Have you try this ? Does it work ?

Thanks.
