### ISSUE TITLE
Suggestion for README

### ISSUE THREAD

**Issue by ghost** [hguenot/yii2-gftp#20]
Requires yii2 2.0.13 or greater (I think that is when BaseObject was introduced).

see also https://forum.yiiframework.com/t/help-yii2-gsftp/83159/2 for a completely different example.

I had a tough time getting this going. Eventually realized I would not be able to.
I don't want it in app config, I want to create them "on the fly" (no examples for that)
The two items above would have moved me along faster.
If and when you have time, add them to the readme.

Looks good. Maybe after I have time to upgrade Yii2 I can revisit.

**Comment by hguenot** [comment]
Hello 

The sample in the forum came from README of https://github.com/hguenot/yii2-gsftp extension.
The required YII version is managed by composer.

BR.
