### ISSUE TITLE
Exsistance of uid and gid

### ISSUE THREAD

**Issue by diegotibi** [hguenot/yii2-gftp#22]
Sometimes uid and gid in sftp are set to null.
This causes an error in SftpFileListConverter line 48.

A simple solution is to user ArrayHelper::getValue():

						'user' => ArrayHelper::getValue($data, 'uid'),
						'group' => ArrayHelper::getValue($data, 'gid'),
						'size' => ArrayHelper::getValue($data, 'size'),

**Comment by hguenot** [comment]
Yes of course please make a Pull Request and I will merge it.

BR.

**Comment by hguenot** [comment]
Merged pull request https://github.com/hguenot/yii2-gsftp/pull/12
