### ISSUE TITLE
FtpComponent/RemoteDriver return type does not match

### ISSUE THREAD

**Issue by Murolike** [hguenot/yii2-gftp#24]
I have problems after updating the extension - Error: Return value of gftp\FtpComponent::put() must be of the type string, null returned.

https://github.com/hguenot/yii2-gftp/blob/master/FtpComponent.php#L312
```php

public function put(
			$local_file,
			?string $remote_file = null,
			int $mode = FTP_ASCII,
			bool $asynchronous = false,
			callable $asyncFn = null): string {
		$this->connectIfNeeded();

		$full_remote_file = $this->handle->put($local_file, $remote_file, $mode, $asynchronous, $asyncFn);
		$this->onFileUploaded(new Event(['sender' => $this, 'data' => $remote_file]));
		return $full_remote_file;
	}
```

Method `put` FtpComponent has returned type `string`, but variable `$full_remote_file = null` because  method `put` interface `RemoteDriver` has returned type `void`;

**Comment by hguenot** [comment]
Fixed in release v3.0.1
