### ISSUE TITLE
how to create dir ? ftp_chdir(): Failed to change directory.

### ISSUE THREAD

**Issue by fbens** [hguenot/yii2-gftp#6]
how to create a unknow dir?

```
$dir = date('Y/ym/d')
```

i don't know either this dir is exist or not 

```
//$dir = 'img/'.date('Y/ym/d');
$dir = 'img/2015/1508/02';
        $arr = explode($split, $dir);
        foreach($arr as $d){

            if(!\Yii::$app->ftp->chdir($d)){
                \Yii::$app->ftp->mkdir($d);    
            }
        }
```

**Comment by hguenot** [comment]
Hello...

You can catch the which gftp\FtpException has been thrown.
But I think it will be better to add a methid fileExists in the drivers...
I will try to write it.

Best regards

*Hervé GUENOT*
Tél: 06.99.23.89.13
Mail: herve@guenot.info


2015-08-02 6:43 GMT+02:00 default7 <notifications@github.com>:

**Comment by hguenot** [comment]
You have to catch `gftp\FtpException`.
I will add method fileExists in driver in order to test file existence.

**Comment by hguenot** [comment]
Method fileExists added in FtpComponent and drivers.
Cf. commit : https://github.com/hguenot/yii2-gftp/commit/fc81a9d8d543595ade6652d6498f3937af1cc87e
